{% set name = "transaction" %}
{% set version = "2.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "726059c461b9ec4e69e5bead6680667a3db01bf2adf901f23e4031228a0f9f9f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  preserve_egg_dir: True
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - zope.interface

test:
  imports:
    - transaction

about:
  home: https://github.com/zopefoundation/transaction
  license_file: LICENSE.txt
  license: ZPL 2.1
  license_family: Other
  summary: 'Transaction management for Python'
  description: |
    A transaction consists of one or more operations that we want to perform
    as a single action. It's an all or nothing proposition: either all the
    operations that are part of the transaction are completed successfully or
    none of them have any effect. In the transaction package, a transaction
    object represents a running transaction that can be committed or aborted
    in the end.
  doc_url: http://zodb.readthedocs.org/en/latest/transactions.html
  doc_source_url: https://github.com/cguardia/ZODB-Documentation/blob/master/book/transactions.rst

extra:
  recipe-maintainers:
    - pmlandwehr
    - nehaljwani
