travis:
  secure:
    BINSTAR_TOKEN: PP0gHkkWT9U4xFxtt/cKlgijKgScSlzugGMQhs080C+2Q50jWrgw2w2OFEgVjYN/ntXp4Ztn5Utq/O/ftkc59xBrhNX9Y6tEVqJfX6ZPtfGhSELDXZRJN8uXvqn9yOYLjrBUHlJN2H7LphNwLVh03dQD2t19ky7xgnff/8Xh1+LnBVNI+SmYirXSp887pselCX2179Cky16O6oiQnVVa/PPFj4xY9HkO2x1lN1GLXSofBWX93W1/oc7ZGhgMrZm64hGZEtGJiYGfneHmAuv3V0izo0Zr/520hT/qkmnxxSrmEoQy7QhmUzbp2b7VuMTAz4O6pgS29ziVpP+j1WDufA8CkAqDT2JmNrSRDsLML5kd8ev/NAVYqg6zDD196jPXCG1CPApsjdYBJ1m5h7XzZ0FKptimXBF8im+teVTN5Eb3l1mvshsZIYALgLmm4PMlp0WWVFkLcC0NuJEB7eLedoqjrkDD+7pJbB2+j2kel7zgHwDPD2AzoDSrR0cH31t/efZWNS+Q/ZmONLtaTkk2bMIRM5WvoEoOTUXA4l50UDLhnlcbmRGcdQLcONyX0HqojMvLTmD7DABMttFXYEaes3FyWlJ7TUFPMxTAtdHysGlgAq5FVPv2su1WKhZM3S7SB2G4R9EAIRjVTNKXStX/W0TeWreWiKnzR/27bhQnoM8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
