travis:
  secure:
    BINSTAR_TOKEN: i48JzAD4ZBY5QbzEgj0XwC0ikKqJ5HZWw3om5A6T2ngSYIf45YV+r1ln8ZQlnhddkX9/GsayR8letkx/dGgQN6zKRuf/CeIdDccdTPYTnlpgZHud6ObyEYcj3diyVD+xGJnfdVmYgDkW6qSSTYtevawEo3/gC9rfSY1ULMBC8yiZiMLObUtcITKk81kos6S0dU1DvDjzhZccLQ0xhPe1NLH7C4Z2oX5oCBkDZyM0b1TVaDaV/xsPiJEaVQ8EB8HsMEhUNTy4Jgafb4T/ulunTo9wsSok/W8vLseKIWv7kS0wC9j+lCunM2jzwZI1mDDYu5s7MfVGlGEAw6PTeVA7D8rzbKbP6n/ltU7DTBihAt2gOwWHcaUr1jexnAeKQLVlLzOEUD6tIiUNJq9wvz4ok0dsFjaaj7Cnc+H26ySHT0FWO+u8Kb+241kPAx3El0hhgN/H92PIUuGAWg3jUjfvuHyHorjSRbvGCEhG/NtnhdB4bH5eWzrZIsABuIdkGVbiL0SoxARzxHoO5Y+5fFZzmmV614JtCuli0Hr2b15arBx3+APdogSN4WicM8cipIWV3gXoZwau9Zo2Hzt3m1o5rLgyc+RWPicALHyQF5g//GfyuuGscOCxrk8+D9ekb8sMQbRtrUAKRn6RQHOOiau6iglm1tbtbkimwmr4CkwHLjc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
